---
# Portainer Docker Container
- name: Create ab/portainer directory
  ansible.builtin.file:
    path: /ab/misc/portainer
    state: directory
    mode: '0755'
  tags: portainer

- name: Copy portainer-password file
  ansible.builtin.copy:
    src: files/{{ deployment_name }}/portainer-password.txt
    dest: /ab/misc/portainer/
    owner: "{{ addl_admin_user }}"
    group: "{{ addl_admin_user }}"
    mode: '0755'
  tags: portainer

- name: Copy docker-compose config file
  template:
    src: "docker-compose.yml.j2"
    dest: "/ab/misc/portainer/docker-compose.yml"
    owner: "{{ addl_admin_user }}"
    group: "{{ addl_admin_user }}"
    mode: 0755
  tags: portainer

- name: Deploy Portainer Docker Compose stack
  docker_compose:
    project_src: /ab/misc/portainer/
  register: output
  tags: portainer

# - name: Remove file portainer-password file
#   ansible.builtin.file:
#     path: /ab/misc/portainer/portainer-password.txt
#     state: absent
#   tags: portainer