---
- name: Create ab/code-server directory
  ansible.builtin.file:
    path: /ab/code-server
    state: directory
    mode: '0755'
  tags: code-server

- name: Create /usr/lib/code-server directory
  ansible.builtin.file:
    path: /usr/lib/code-server
    state: directory
    mode: '0755'
  tags: code-server

- name: Install pre-reqs
  apt:
    name:
    - net-tools
    - openssl
    - build-essential
    state: present
  tags: code-server

- name: Download and unarchive code-server
  ansible.builtin.unarchive:
    src: https://github.com/cdr/code-server/releases/download/v{{ code_server_version }}/code-server-{{ code_server_version }}-linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes
  tags: code-server, code-server-download

- name: Get stats of the FS object
  ansible.builtin.stat:
    path: /usr/lib/code-server/code-server-{{ code_server_version }}-linux-amd64/bin/code-server
  register: code

- name: Move code-server
  ansible.builtin.command: mv /tmp/code-server-{{ code_server_version }}-linux-amd64 /usr/lib/code-server
  tags: code-server, code-server-move
  when: code.stat.exists == False

- name: Link code-server
  ansible.builtin.command: ln -s /usr/lib/code-server/code-server-{{ code_server_version }}-linux-amd64/bin/code-server /usr/local/bin/code-server
  tags: code-server
  when: code.stat.exists == False

- name: modify code-server
  ansible.builtin.command: chmod a+x /usr/lib/code-server
  tags: code-server

- name: Copy code-server service file
  template:
    src: "code-server.service.j2"
    dest: "{{ systemd_dir }}/code-server.service"
    owner: root
    group: root
    mode: 0755
  tags: code-server

- name: Enable and check code-server service
  systemd:
    name: code-server
    daemon_reload: yes
    state: restarted
    enabled: yes
    no_block: yes
  tags: code-server

- name: Check to ensurecode-server service actually started
  ansible.builtin.service:
    name: code-server
    state: started
  tags: code-server