---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install docker prereq apt packages
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg-agent
    state: present
    update_cache: true

- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

- name: Install Docker
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present
    update_cache: yes

- name: Add ansible user to docker group
  user:
    name: "{{ ansible_user }}"
    group: docker

- name: Add additional user to docker group
  user:
    name: "{{ addl_admin_user }}"
    group: docker

- name: Install python Docker / Docker-compse module
  pip:
    name:
        - docker
        - docker-compose
        - kubectl

#- name: Download docker-compose {{ docker_compose_version }}
#  get_url:
#    url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
#    dest: /usr/local/bin/docker-compose
#    mode: '+x'

#- name: Check docker-compose exists
#  stat: path=/usr/local/bin/docker-compose
#  register: docker_compose