---
- hosts: lab_servers
  gather_facts: yes
  become: yes
  roles:
    - role: lab_server
    - role: security
    - role: docker
    - role: containers/certbot
    - role: code-server
    - role: containers/rancher
    - role: containers/portainer
    - role: k3d