---
- name: Clone Lab Repo
  ansible.builtin.git:
    repo: "{{ git_lab_url }}"
    dest: /ab/labs
    force: yes
  tags: lab-repo

- name: Change owner of /ab/labs folder
  shell: chown -R abtraining:abtraining /ab/labs
  tags: lab-repo

- name: Change owner of /ab/labs folder
  shell: rm -rf /ab/labs/.git
  tags: lab-repo

- name: Find all of the README files inside this directory
  find:
    paths: "/ab/labs/"
    patterns: "README.md"
    recurse: yes
  register: repos
  tags: replace, lab-repo

- name: Replace LABSERVERNAME with the local DNS hostname in the files
  replace:
    path: "{{ item.path }}"
    regexp: 'LABSERVERNAME'
    replace: '{{ ansible_hostname }}.{{ environment_domain }}'
  with_items: "{{ repos.files }}"
  tags: replace, lab-repo