---
- name: Remove all files in /ab/labs
  ansible.builtin.file:
    path: /ab/labs/
    state: absent
  tags: lab-server, lab-repo

- name: Clone Lab Repo
  ansible.builtin.git:
    repo: "{{ git_lab_url }}"
    dest: /ab/labs
    force: yes
  tags: lab-server, lab-repo

- name: Change owner of /ab/labs folder
  shell: chown -R abtraining:abtraining /ab/labs
  tags: lab-server, lab-repo

- name: Remove .git folder from lab repo
  ansible.builtin.file:
    path: /ab/labs/.git
    state: absent
  tags: lab-server, lab-repo

- name: Find all of the README files inside this directory
  find:
    paths: "/ab/labs/"
    patterns: "README.md,*.yml"
    recurse: yes
  register: repos
  tags: lab-server, lab-repo

- name: Replace LABSERVERNAME with the local DNS hostname in the files
  replace:
    path: "{{ item.path }}"
    regexp: 'LABSERVERNAME'
    replace: '{{ ansible_hostname }}.{{ environment_domain }}'
  with_items: "{{ repos.files }}"
  tags: lab-server, lab-repo