---
# - name: Ensure group {{ addl_admin_user }} exists
#   ansible.builtin.group:
#     name: "{{ addl_admin_user }}"
#     state: present

- name: Add an additional user with sudo capabilities
  user:
    name: "{{ addl_admin_user }}"
    groups: sudo,docker
    append: yes
    shell: /bin/bash
    create_home: yes

- name: Add addl_admin_user user to the sudoers
  lineinfile:
    path: /etc/sudoers.d/{{ addl_admin_user }}
    line: '{{ addl_admin_user }} ALL=(ALL) NOPASSWD: ALL, !/bin/su, !/usr/sbin/shutdown, !/usr/sbin/halt, !/usr/sbin/reboot, !/usr/sbin/poweroff '
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
  tags: addluserprivs

- name: Create directory .ssh
  ansible.builtin.file:
    path: "/home/{{ addl_admin_user }}/.ssh"
    state: directory
    owner: "{{ addl_admin_user }}"
    group: "{{ addl_admin_user }}"
    mode: "0700"

- name: Copy authorized keys to new user
  copy:
    src: /root/.ssh/authorized_keys
    dest: "/home/{{ addl_admin_user }}/.ssh/authorized_keys"
    remote_src: yes
    owner: "{{ addl_admin_user }}"
    mode: "0600"

- name: Add History File Config
  blockinfile:
    path: /home/{{ addl_admin_user }}/.bashrc
    block: |
      export HISTCONTROL=ignoredups:erasedups  # no duplicate entries
      export HISTSIZE=100000                   # big big history
      export HISTFILESIZE=100000               # big big history
      shopt -s histappend                      # append to history, don't overwrite it

      # Save and reload the history after each command finishes
      export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"