#!/usr/bin/env python3

import configparser
import os.path
import os
from pathlib import Path
from pygit2 import Repository
import subprocess

## Update this list should additional roles be added in Ansible.
configList = ['init_master', 'ha_masters', 'worker']

## Set required variables.
ipAddresses = []
home = str(Path.home())
knownHosts = f'{home}/.ssh/known_hosts'
getBranch = Repository('.').head.shorthand.lower()
tmpFile = f'/tmp/{getBranch}'

## Read the Ansible inventory file.
config = configparser.ConfigParser(allow_no_value=True)
config.read(f'ansible/inventory/{getBranch}/{getBranch}-inventory')

## Get a list of IP addresses from the Ansible inventory file, generated by Terraform.
for item in configList:
    for key in config[item]:
        ipAddresses.append(key)

## Write out the IP addresses to a TMP file, which we'll remove shortly.
with open(f'/tmp/{getBranch}', mode='w', encoding='utf-8') as tmpFile:
    tmpFile.write('\n'.join(ipAddresses))
    tmpFile.write('\n')
tmpFile.close

## Run SSH-KEYSCAN against the TMP file, dumping the results into the SSH Known Hosts file.
result = subprocess.run(
                [f"ssh-keyscan -t rsa -f /tmp/{getBranch} >> {knownHosts} "], shell=True
            )

## Remove the TMP file.
os.remove(f'/tmp/{getBranch}')